# Generated by Django 2.0.6 on 2018-07-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviationid', models.CharField(max_length=64)),
                ('content_src', models.TextField()),
                ('url', models.TextField()),
                ('published_time', models.IntegerField()),
                ('is_mature', models.BooleanField()),
                ('viewable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoneDevs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('last_updated', models.IntegerField()),
                ('last_published_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IgnoredPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviationid', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Null',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportedPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviationid', models.CharField(max_length=64)),
                ('report_count', models.IntegerField()),
            ],
        ),
    ]
