# Generated by Django 2.0.6 on 2018-07-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Null',
        ),
    ]
