# Generated by Django 2.0.7 on 2018-07-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_suggestionbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
            ],
        ),
    ]
